### ISSUE TITLE
Facebook API $ref contains spaces

### ISSUE THREAD

**Issue by dflorey** [api-stack/api-stack#51]
The swagger parser fails to reference the definitions properly as they contain spaces...

```
            items:
              $ref: '#/definitions/Video Copyright Rule'
```

...while they contain underscores in the definitions...

```

  Video_Copyright_Rule:
    properties:
      id:
        description: The id of video copyright rules objectDefault
```
